# Generated by Django 2.1.5 on 2020-03-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_adv', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='intro',
            field=models.TextField(default='nothing yet'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, upload_to='restaurant_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
