# Generated by Django 2.1.5 on 2020-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_adv', '0006_auto_20200321_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='like_restaurants',
            field=models.ManyToManyField(to='rest_adv.Restaurant'),
        ),
    ]
