# Generated by Django 2.1.5 on 2020-03-21 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_adv', '0007_userprofile_like_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='deletedAt',
            field=models.DateTimeField(default=None, null=True, verbose_name='Delete time'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='deletedAt',
            field=models.DateTimeField(default=None, null=True, verbose_name='Delete time'),
        ),
        migrations.AddField(
            model_name='review',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deletedAt',
            field=models.DateTimeField(default=None, null=True, verbose_name='Delete time'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
