# Generated by Django 2.1.5 on 2020-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_adv', '0008_auto_20200321_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='fast food', max_length=64),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, default='statics/images/1.jpeg', upload_to='restaurant_images'),
        ),
    ]
